dependencies:
- name: devops-spring
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.2
- name: devops-springboot
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- name: devops-springboot-test
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- name: devops-springex
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- alias: expose
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.89
- alias: cleanup
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.89
- name: svc-heloc-offers-devops
  repository: http://jenkins-x-chartmuseum:8080
  version: 1.3.6
- name: svc-heloc-offers-test
  repository: http://jenkins-x-chartmuseum:8080
  version: 1.3.37
